db.url=jdbc:mysql://localhost:3306/ecommerce_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
db.user=root
db.password=alex

jwt.secret=fashionhub-super-secret-key-2026-ecommerce

mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.from=noreply@fashionhub.com
mail.user=
mail.password=
